/**
 * Today Page - Morning Session
 * Sprint: Data Input Refactor - Audit/Structured Data
 * 
 * New structured inputs:
 * - Quote absorbed checkbox inside quote card
 * - Main intention input (50 chars max) replaces journal textarea
 * - Clarity level (1-5 stars) replaces meditation checkbox
 * - Action category dropdown for critical action
 */
import { useState, useEffect, useRef, useMemo } from 'react';
import { Layout } from '@/components/Layout';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Slider } from '@/components/ui/slider';
import { Badge } from '@/components/ui/badge';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { Clock, Zap, Headphones, RefreshCw, Copy, Timer, Target, Lightbulb, AlertCircle } from 'lucide-react';
import { MeditationMode } from '@/components/MeditationMode';
import { MorningCockpit } from '@/components/MorningCockpit';
import { ClarityRating } from '@/components/ClarityRating';
import { ActionCategorySelect, ActionCategory } from '@/components/ActionCategorySelect';
import { IntentionInput } from '@/components/IntentionInput';
import { GratitudeCard, GratitudeCategory } from '@/components/GratitudeCard';
import { useToast } from '@/hooks/use-toast';
import { useThemes } from '@/hooks/useThemes';
import { useDailyEntry, useDailyEntries } from '@/hooks/useDailyEntry';
import { useDailySession } from '@/hooks/useDailySession';
import { useSettings } from '@/hooks/useSettings';
import { useAutoThemeSelection, selectVisualization, confirmVisualization } from '@/hooks/useAutoSelection';
import { useTTS } from '@/hooks/useTTS';
import { useBellSound } from '@/hooks/useBellSound';
import { TTSControls } from '@/components/TTSControls';
import { Visualization } from '@/lib/database.types';
import { QuoteOfTheDay } from '@/components/QuoteOfTheDay';
import { useJournalEntry } from '@/hooks/useJournalEntry';
import { calculateMorningProgress } from '@/lib/sessionProgress';
import { format } from 'date-fns';
import { ptBR } from 'date-fns/locale';

export default function Today() {
  const { toast } = useToast();
  const { activeThemes, themes } = useThemes();
  const { settings } = useSettings();
  const { entries } = useDailyEntries(settings?.theme_lookback_days || 14);
  const { entry, createEntry, updateEntry, isLoading: entryLoading } = useDailyEntry();
  const { session, updateSession, getOrCreateSession, completeMeditation, completeJournal, toggleAction } = useDailySession();
  const { entry: journalEntry } = useJournalEntry();

  const [themeId, setThemeId] = useState<string>('');
  const [visualization, setVisualization] = useState<Visualization | null>(null);
  const [energy, setEnergy] = useState<number>(5);
  const [identity, setIdentity] = useState('');
  const [criticalAction, setCriticalAction] = useState('');
  const [actionDone, setActionDone] = useState(false);
  const [showMeditation, setShowMeditation] = useState(false);
  const [autoGenerated, setAutoGenerated] = useState(false);
  const [customDuration, setCustomDuration] = useState<number | null>(null);
  
  // Sprint: Data Input Refactor - new structured fields
  const [quoteAbsorbed, setQuoteAbsorbed] = useState(false);
  const [mainIntention, setMainIntention] = useState('');
  const [clarityLevel, setClarityLevel] = useState<number | null>(null);
  const [actionCategory, setActionCategory] = useState<ActionCategory | null>(null);
  // Sprint: Gratitude Section
  const [morningGratitudeText, setMorningGratitudeText] = useState('');
  const [morningGratitudeCategory, setMorningGratitudeCategory] = useState<GratitudeCategory | null>(null);

  const intentionRef = useRef<HTMLDivElement>(null);
  const suggestedTheme = useAutoThemeSelection({ themes, entries, settings });

  const { playBell } = useBellSound();
  
  const tts = useTTS({
    settings: {
      tts_enabled: settings?.tts_enabled ?? true,
      tts_rate: settings?.tts_rate ?? 0.62,
      tts_pitch: settings?.tts_pitch ?? 1.00,
      tts_volume: settings?.tts_volume ?? 1.00,
      tts_prefer_female: settings?.tts_prefer_female ?? true,
      tts_voice_uri: settings?.tts_voice_uri ?? null,
      tts_pause_base_ms: settings?.tts_pause_base_ms ?? 220,
      tts_pause_per_word_ms: settings?.tts_pause_per_word_ms ?? 65,
      tts_pause_sentence_extra_ms: settings?.tts_pause_sentence_extra_ms ?? 450,
      tts_pause_paragraph_extra_ms: settings?.tts_pause_paragraph_extra_ms ?? 900,
      tts_breath_pause_ms: settings?.tts_breath_pause_ms ?? 1700,
      tts_microchunk_min_words: settings?.tts_microchunk_min_words ?? 8,
      tts_microchunk_max_words: settings?.tts_microchunk_max_words ?? 14,
      tts_end_silence_ms: settings?.tts_end_silence_ms ?? 30000,
      tts_outro_enabled: settings?.tts_outro_enabled ?? true,
      tts_outro_text: settings?.tts_outro_text ?? '',
    },
    onEndSilenceComplete: playBell,
  });

  // Stop TTS when visualization changes
  useEffect(() => {
    if (tts.isSpeaking) {
      tts.stop();
    }
  }, [visualization?.id]);

  // Initialize form from entry
  useEffect(() => {
    if (entry) {
      setThemeId(entry.theme_id || '');
      setEnergy(entry.energy ?? 5);
      setIdentity(entry.identity || '');
      setCriticalAction(entry.critical_action || '');
      setActionDone(entry.action_done);
    }
  }, [entry]);

  // Initialize from session (new structured fields)
  useEffect(() => {
    if (session) {
      setQuoteAbsorbed(session.quote_absorbed ?? false);
      setMainIntention(session.main_intention || '');
      setClarityLevel(session.clarity_level ?? null);
      setActionCategory(session.action_category as ActionCategory | null);
      // Sprint: Gratitude Section
      setMorningGratitudeText(session.morning_gratitude_text || '');
      setMorningGratitudeCategory(session.morning_gratitude_category as GratitudeCategory | null);
    }
  }, [session]);

  // Auto-suggest theme on load
  useEffect(() => {
    if (!entry && !themeId && suggestedTheme && settings?.default_theme_mode === 'auto') {
      setThemeId(suggestedTheme.id);
    }
  }, [suggestedTheme, entry, themeId, settings]);

  // Auto-generate visualization when theme is set
  useEffect(() => {
    const autoGenViz = async () => {
      if (!themeId || !settings || autoGenerated) return;
      
      // Check if session already has visualization
      if (session?.morning_visualization_id) {
        // Load existing visualization
        const { supabase } = await import('@/integrations/supabase/client');
        const { data } = await supabase
          .from('visualizations')
          .select('*')
          .eq('id', session.morning_visualization_id)
          .single();
        if (data) {
          setVisualization(data as Visualization);
          // Load saved duration from session, or use settings default
          if (session.morning_meditation_duration) {
            setCustomDuration(session.morning_meditation_duration);
          } else {
            setCustomDuration(settings.preferred_duration_min);
          }
          setAutoGenerated(true);
        }
        return;
      }

      // Auto-select visualization
      const viz = await selectVisualization(themeId, energy, settings);
      if (viz) {
        setVisualization(viz);
        // Use settings preferred duration as default
        setCustomDuration(settings.preferred_duration_min);
        await confirmVisualization(viz.id);
        setAutoGenerated(true);
        
        // Create/update session with visualization
        const sess = await getOrCreateSession({
          theme_id: themeId,
          morning_visualization_id: viz.id,
          morning_energy: energy,
          morning_meditation_duration: settings.preferred_duration_min,
        });
        
        // Create/update daily entry
        if (entry) {
          await updateEntry.mutateAsync({ visualization_id: viz.id, theme_id: themeId });
        } else {
          await createEntry.mutateAsync({ theme_id: themeId, visualization_id: viz.id, energy });
        }
      }
    };

    autoGenViz();
  }, [themeId, settings, session?.morning_visualization_id]);

  // Sync journal completion to session when intention is filled
  useEffect(() => {
    if (mainIntention && session && !session.morning_journal_completed) {
      completeJournal();
    }
  }, [mainIntention, session]);

  // Sync action done to session
  useEffect(() => {
    if (session && session.morning_action_completed !== actionDone) {
      toggleAction(actionDone);
    }
  }, [actionDone]);

  const handleChangeVisualization = async () => {
    if (!themeId || !settings) return;
    
    tts.stop();
    // Reset to settings preferred duration when changing visualization
    setCustomDuration(settings.preferred_duration_min);
    
    const viz = await selectVisualization(themeId, energy, settings, visualization?.id);
    if (viz) {
      setVisualization(viz);
      await confirmVisualization(viz.id);
      
      if (session) {
        await updateSession.mutateAsync({ 
          morning_visualization_id: viz.id,
          morning_meditation_duration: settings.preferred_duration_min,
        });
      }
      
      if (entry) {
        await updateEntry.mutateAsync({ visualization_id: viz.id });
      }
      
      toast({ title: 'Visualização trocada', description: viz.title });
    } else {
      toast({ title: 'Sem mais visualizações', description: 'Nenhuma outra disponível', variant: 'destructive' });
    }
  };

  const handlePlayTTS = () => {
    if (visualization) {
      tts.speak(visualization.script, visualization.title);
    }
  };

  const handleStartMeditation = async () => {
    tts.stop();
    setShowMeditation(true);
    // Mark meditation complete immediately when starting
    await completeMeditation();
  };

  const handleCloseMeditation = (completed?: boolean) => {
    setShowMeditation(false);
    // Could optionally prompt for clarity level here
    // For now the clarity rating is visible below the visualization card
  };

  const handleGoToIntention = () => {
    intentionRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  const handleQuoteAbsorbedChange = async (absorbed: boolean) => {
    setQuoteAbsorbed(absorbed);
    if (session) {
      await updateSession.mutateAsync({ quote_absorbed: absorbed });
    } else {
      const sess = await getOrCreateSession({ quote_absorbed: absorbed });
    }
  };

  const handleSave = async () => {
    const data = {
      theme_id: themeId || null,
      visualization_id: visualization?.id || entry?.visualization_id || null,
      energy,
      identity: identity || null,
      critical_action: criticalAction || null,
      action_done: actionDone,
    };

    if (entry) {
      await updateEntry.mutateAsync(data);
    } else {
      await createEntry.mutateAsync(data);
    }
    
    // Update session with all structured data
    if (session) {
      await updateSession.mutateAsync({ 
        morning_energy: energy,
        quote_absorbed: quoteAbsorbed,
        main_intention: mainIntention || null,
        clarity_level: clarityLevel,
        action_category: actionCategory,
        critical_action_completed: actionDone,
        // Sprint: Gratitude Section
        morning_gratitude_text: morningGratitudeText || null,
        morning_gratitude_category: morningGratitudeCategory,
      });
    }
    
    toast({ title: 'Salvo!', description: 'Entrada do dia atualizada' });
  };

  const handleCopyWhatsApp = () => {
    if (!session?.morning_completed) {
      toast({ 
        title: 'Complete a manhã primeiro', 
        description: 'Finalize a sessão da manhã para compartilhar',
        variant: 'destructive' 
      });
      return;
    }
    
    const themeName = themes.find(t => t.id === themeId)?.name || '-';
    const clarityLabels = ['', 'Nenhuma', 'Pouca', 'Razoável', 'Boa', 'Excelente'];
    const text = `🌅 *Blueprint Digital - ${format(new Date(), "dd/MM/yyyy")}*

🎯 Tema: ${themeName}
⚡ Energia: ${energy}/10
💡 Intenção: ${mainIntention || '-'}
✨ Clareza: ${clarityLevel ? clarityLabels[clarityLevel] : '-'}
📌 Categoria: ${actionCategory || '-'}
✅ Ação: ${criticalAction || '-'}`;

    navigator.clipboard.writeText(text);
    toast({ title: 'Copiado!', description: 'Resumo copiado para o WhatsApp' });
  };

  const hasIntention = !!mainIntention;

  // Calculate morning progress for validation
  const morningProgress = useMemo(() => 
    calculateMorningProgress(session, { criticalAction }),
    [session, criticalAction]
  );

  return (
    <Layout>
      {/* Meditation Mode Overlay */}
      {showMeditation && visualization && (
        <MeditationMode
          title={visualization.title}
          script={visualization.script}
          durationMinutes={customDuration ?? visualization.duration_min}
          ttsSettings={{
            tts_enabled: settings?.tts_enabled ?? true,
            tts_rate: settings?.tts_rate ?? 0.62,
            tts_pitch: settings?.tts_pitch ?? 1.00,
            tts_volume: settings?.tts_volume ?? 1.00,
            tts_prefer_female: settings?.tts_prefer_female ?? true,
            tts_voice_uri: settings?.tts_voice_uri ?? null,
            tts_pause_base_ms: settings?.tts_pause_base_ms ?? 220,
            tts_pause_per_word_ms: settings?.tts_pause_per_word_ms ?? 65,
            tts_pause_sentence_extra_ms: settings?.tts_pause_sentence_extra_ms ?? 450,
            tts_pause_paragraph_extra_ms: settings?.tts_pause_paragraph_extra_ms ?? 900,
            tts_breath_pause_ms: settings?.tts_breath_pause_ms ?? 1700,
            tts_microchunk_min_words: settings?.tts_microchunk_min_words ?? 8,
            tts_microchunk_max_words: settings?.tts_microchunk_max_words ?? 14,
            tts_end_silence_ms: settings?.tts_end_silence_ms ?? 30000,
          }}
          onClose={handleCloseMeditation}
        />
      )}
      <div className="max-w-2xl mx-auto space-y-6">
        <div className="flex items-center justify-between">
          <h2 className="text-2xl font-semibold">
            {format(new Date(), "EEEE, d 'de' MMMM", { locale: ptBR })}
          </h2>
          {session?.morning_completed && (
            <Badge className="bg-primary/20 text-primary border-primary/30">
              Manhã concluída
            </Badge>
          )}
        </div>

        {/* Morning Cockpit */}
        <MorningCockpit
          session={session}
          hasVisualization={!!visualization}
          hasJournalEntry={hasIntention}
          criticalAction={criticalAction}
          onStartVisualization={handleStartMeditation}
          onPlayVisualization={handleStartMeditation}
          onGoToJournal={handleGoToIntention}
        />

        {/* Quote of the Day with absorbed checkbox */}
        <QuoteOfTheDay 
          themeId={themeId || null} 
          quoteAbsorbed={quoteAbsorbed}
          onQuoteAbsorbedChange={handleQuoteAbsorbedChange}
        />

        {/* Visualization - Always shown if available */}
        {visualization && (
          <Card>
            <CardHeader className="pb-3">
              <div className="flex items-center justify-between">
                <CardTitle className="text-lg">Visualização do Dia</CardTitle>
                <Button variant="ghost" size="sm" onClick={handleChangeVisualization}>
                  <RefreshCw className="h-4 w-4 mr-2" />
                  Trocar
                </Button>
              </div>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-3">
                <div className="flex items-center justify-between">
                  <h3 className="font-medium">{visualization.title}</h3>
                  <div className="flex items-center gap-2 text-sm text-muted-foreground">
                    <Zap className="h-4 w-4" />
                    {visualization.energy_min}-{visualization.energy_max}
                  </div>
                </div>
                
                {/* Duration selector */}
                <div className="flex items-center gap-3 p-3 bg-muted/30 rounded-lg">
                  <Timer className="h-4 w-4 text-muted-foreground" />
                  <Label className="text-sm text-muted-foreground">Duração:</Label>
                  <Select 
                    value={String(customDuration ?? visualization.duration_min)}
                    onValueChange={async (v) => {
                      const duration = Number(v);
                      setCustomDuration(duration);
                      // Persist to session
                      if (session) {
                        await updateSession.mutateAsync({ morning_meditation_duration: duration });
                      }
                    }}
                  >
                    <SelectTrigger className="w-24 h-8">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="2">2 min</SelectItem>
                      <SelectItem value="3">3 min</SelectItem>
                      <SelectItem value="4">4 min</SelectItem>
                      <SelectItem value="5">5 min</SelectItem>
                      <SelectItem value="7">7 min</SelectItem>
                      <SelectItem value="10">10 min</SelectItem>
                    </SelectContent>
                  </Select>
                </div>

                {visualization.tags && visualization.tags.length > 0 && (
                  <div className="flex flex-wrap gap-1">
                    {visualization.tags.map((tag) => (
                      <Badge key={tag} variant="outline" className="text-xs">{tag}</Badge>
                    ))}
                  </div>
                )}
                <div className="bg-muted/50 p-4 rounded-lg space-y-3">
                  <p className="text-sm leading-relaxed whitespace-pre-line">
                    {visualization.script}
                  </p>
                  
                </div>
                
                <Button onClick={handleStartMeditation} className="w-full gap-2">
                  <Headphones className="h-4 w-4" />
                  Iniciar Meditação Guiada
                </Button>
                
                {/* Clarity Rating - replaces simple checkbox */}
                <div className="p-4 bg-muted/30 rounded-lg space-y-3">
                  <Label className="text-sm font-medium">Nível de Clareza da Visualização</Label>
                  <ClarityRating 
                    value={clarityLevel} 
                    onChange={async (val) => {
                      setClarityLevel(val);
                      if (session) {
                        await updateSession.mutateAsync({ clarity_level: val });
                      }
                    }} 
                  />
                </div>
              </div>
            </CardContent>
          </Card>
        )}

        {/* Energy */}
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-lg flex items-center justify-between">
              <span>Energia</span>
              <span className="text-primary font-bold">{energy}/10</span>
            </CardTitle>
          </CardHeader>
          <CardContent>
            <Slider
              value={[energy]}
              onValueChange={([v]) => setEnergy(v)}
              max={10}
              min={0}
              step={1}
              className="py-4"
            />
          </CardContent>
        </Card>

        {/* Main Intention - replaces micro journal textarea */}
        <div ref={intentionRef}>
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-lg flex items-center gap-2">
                <Lightbulb className="h-5 w-5 text-primary" />
                A Única Coisa (Intenção)
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-2">
              <IntentionInput
                value={mainIntention}
                onChange={async (val) => {
                  setMainIntention(val);
                  if (session) {
                    await updateSession.mutateAsync({ main_intention: val || null });
                  }
                }}
                placeholder="A única coisa que importa hoje..."
              />
              <p className="text-xs text-muted-foreground">
                Qual é o foco principal do seu dia?
              </p>
            </CardContent>
          </Card>
        </div>

        {/* Morning Gratitude - Sprint: Gratitude Section */}
        <GratitudeCard
          variant="morning"
          text={morningGratitudeText}
          category={morningGratitudeCategory}
          onTextChange={async (val) => {
            setMorningGratitudeText(val);
            if (session) {
              await updateSession.mutateAsync({ morning_gratitude_text: val || null });
            }
          }}
          onCategoryChange={async (cat) => {
            setMorningGratitudeCategory(cat);
            if (session) {
              await updateSession.mutateAsync({ morning_gratitude_category: cat });
            }
          }}
        />

        {/* Identity & Critical Action with Category */}
        <Card>
          <CardContent className="pt-6 space-y-4">
            <div className="space-y-2">
              <Label htmlFor="identity">Identidade do dia</Label>
              <Input
                id="identity"
                placeholder="Quem você é hoje?"
                value={identity}
                onChange={(e) => setIdentity(e.target.value)}
              />
            </div>
            
            <div className="space-y-3">
              <Label htmlFor="action">Ação crítica</Label>
              <div className="flex gap-2">
                <Input
                  id="action"
                  placeholder="verbo + número/tempo (ex: estudar 2h)"
                  value={criticalAction}
                  onChange={(e) => setCriticalAction(e.target.value)}
                  className="flex-1"
                />
                <ActionCategorySelect 
                  value={actionCategory}
                  onChange={async (cat) => {
                    setActionCategory(cat);
                    if (session) {
                      await updateSession.mutateAsync({ action_category: cat });
                    }
                  }}
                />
              </div>
              <p className="text-xs text-muted-foreground">
                Dica: use formato mensurável (verbo + número/tempo)
              </p>
            </div>
          </CardContent>
        </Card>

        {/* Validation feedback */}
        {!morningProgress.isComplete && morningProgress.missingFields.length > 0 && (
          <Alert variant="default" className="border-muted">
            <AlertCircle className="h-4 w-4" />
            <AlertDescription>
              <span className="font-medium">Campos pendentes:</span>{' '}
              {morningProgress.missingFields.slice(0, 3).join(', ')}
              {morningProgress.missingFields.length > 3 && ` (+${morningProgress.missingFields.length - 3})`}
            </AlertDescription>
          </Alert>
        )}

        {/* Actions */}
        <div className="flex gap-3">
          <Button 
            onClick={handleSave} 
            className="flex-1"
            variant={morningProgress.isComplete ? "default" : "outline"}
          >
            {morningProgress.isComplete ? 'Salvar ✓' : 'Salvar Rascunho'}
          </Button>
          {morningProgress.isComplete && (
            <Button variant="outline" onClick={handleCopyWhatsApp}>
              <Copy className="h-4 w-4 mr-2" />
              WhatsApp
            </Button>
          )}
        </div>
      </div>
    </Layout>
  );
}
