-- =====================================================
-- ETAPA 1: INSERIR TEMAS (20 temas)
-- =====================================================

INSERT INTO public.themes (id, name, description, is_active, created_at, updated_at) VALUES
('11111111-1111-1111-1111-111111111101', 'Abundância', 'Mentalidade de possibilidades', true, now(), now()),
('11111111-1111-1111-1111-111111111102', 'Aceitação', 'Ver a realidade como ela é', true, now(), now()),
('11111111-1111-1111-1111-111111111103', 'Autocompaixão', 'Firmeza sem crueldade', true, now(), now()),
('11111111-1111-1111-1111-111111111104', 'Clareza', 'Visão nítida dos objetivos', true, now(), now()),
('11111111-1111-1111-1111-111111111105', 'Coragem', 'Agir apesar do medo', true, now(), now()),
('11111111-1111-1111-1111-111111111106', 'Desapego', 'Soltar o controle', true, now(), now()),
('11111111-1111-1111-1111-111111111107', 'Disciplina', 'Manter consistência', true, now(), now()),
('11111111-1111-1111-1111-111111111108', 'Energia', 'Vitalidade e movimento', true, now(), now()),
('11111111-1111-1111-1111-111111111109', 'Fluidez', 'Adaptar-se com leveza', true, now(), now()),
('11111111-1111-1111-1111-111111111110', 'Foco', 'Atenção com intenção', true, now(), now()),
('11111111-1111-1111-1111-111111111111', 'Gratidão', 'Valorizar o que há de bom', true, now(), now()),
('11111111-1111-1111-1111-111111111112', 'Integridade', 'Coerência e verdade', true, now(), now()),
('11111111-1111-1111-1111-111111111113', 'Intuição', 'Escutar corpo e mente', true, now(), now()),
('11111111-1111-1111-1111-111111111114', 'Paciência', 'Construir no tempo certo', true, now(), now()),
('11111111-1111-1111-1111-111111111115', 'Paz Interior', 'Estabilidade emocional', true, now(), now()),
('11111111-1111-1111-1111-111111111116', 'Presença', 'Estar no momento', true, now(), now()),
('11111111-1111-1111-1111-111111111117', 'Prioridade', 'Escolher o que importa', true, now(), now()),
('11111111-1111-1111-1111-111111111118', 'Rendição', 'Confiar no processo', true, now(), now()),
('11111111-1111-1111-1111-111111111119', 'Silêncio', 'Clareza real', true, now(), now()),
('11111111-1111-1111-1111-111111111120', 'Verdade', 'Agir com lucidez', true, now(), now())
ON CONFLICT (id) DO NOTHING;

-- =====================================================
-- ETAPA 2: INSERIR VISUALIZAÇÕES (51 meditações ativas)
-- =====================================================

-- Abundância (3)
INSERT INTO public.visualizations (id, theme_id, title, script, duration_min, energy_min, energy_max, tags, is_active, created_at, updated_at) VALUES
('22222222-2222-2222-2222-222222222201', '11111111-1111-1111-1111-111111111101', 'O Jardim Interior', 
'Feche os olhos e respire fundo…

Imagine que você está caminhando por um vasto jardim interior… um lugar que representa tudo o que você já cultivou na vida…

Olhe ao redor… veja as plantas que floresceram… os frutos que amadureceram… as sementes que ainda estão germinando…

Perceba que este jardim não tem limites… ele se expande a cada passo que você dá… a cada respiração…

Agora, visualize uma fonte no centro deste jardim… dela jorra uma água cristalina e infinita… essa água é a energia da abundância…

Aproxime-se… deixe suas mãos tocarem essa água… sinta como ela flui sem esforço… sem fim…

Essa mesma energia está disponível para você… sempre esteve… você só precisa se lembrar de acessá-la…

Respire profundamente e traga essa sensação de abundância para dentro de você…

Você é parte desse fluxo infinito…', 
4, 3, 7, ARRAY['manhã', 'visualização', 'abundância'], true, now(), now()),

('22222222-2222-2222-2222-222222222202', '11111111-1111-1111-1111-111111111101', 'O Universo Provedor', 
'Respire fundo e feche os olhos…

Imagine-se flutuando suavemente no espaço… cercado por estrelas e galáxias infinitas…

Cada estrela representa uma possibilidade… uma oportunidade… um recurso disponível para você…

Perceba como são infinitas… não há escassez aqui… apenas expansão…

Agora, escolha uma estrela que brilha especialmente para você… aproxime-se dela…

Ao tocá-la, sinta seu calor e sua luz entrando em você… preenchendo cada célula do seu corpo…

Essa luz é abundância pura… ela não diminui quando você recebe… ela se multiplica…

Traga essa consciência de volta… sabendo que o universo é abundante… e você faz parte dele…', 
4, 2, 6, ARRAY['noite', 'visualização', 'universo'], true, now(), now()),

('22222222-2222-2222-2222-222222222203', '11111111-1111-1111-1111-111111111101', 'O Rio da Prosperidade', 
'Feche os olhos e respire profundamente…

Visualize-se às margens de um grande rio… um rio de águas douradas e cristalinas…

Este é o rio da prosperidade… ele flui eternamente… sem nunca se esgotar…

Observe como a água passa por você… carregando oportunidades… recursos… conexões…

Agora, entre nesse rio… sinta a água morna envolvendo seu corpo…

Você não precisa nadar contra a correnteza… apenas flutue… deixe-se levar…

Perceba que quanto mais você relaxa… mais o rio te sustenta… mais você recebe…

A abundância não vem do esforço desesperado… ela vem da confiança e do alinhamento…

Respire fundo e traga essa sensação de fluidez para o seu dia…', 
4, 4, 8, ARRAY['manhã', 'visualização', 'prosperidade'], true, now(), now()),

-- Aceitação (3)
('22222222-2222-2222-2222-222222222204', '11111111-1111-1111-1111-111111111102', 'O Espelho da Verdade', 
'Respire fundo e feche os olhos…

Imagine-se diante de um grande espelho… um espelho especial que reflete não apenas sua imagem… mas a verdade do momento presente…

Olhe para o reflexo com curiosidade… sem julgamento…

O que você vê? Quais são as realidades da sua vida agora?

Algumas podem ser agradáveis… outras podem ser desconfortáveis…

Mas todas são verdadeiras… e a verdade é o ponto de partida para qualquer mudança real…

Respire fundo e diga internamente: "Eu aceito o que é"…

Isso não significa que você concorda… ou que desiste de mudar…

Significa que você para de lutar contra a realidade… e começa a trabalhar com ela…

Sinta o alívio dessa aceitação… a liberdade de ver as coisas como realmente são…', 
4, 2, 6, ARRAY['reflexão', 'aceitação', 'verdade'], true, now(), now()),

('22222222-2222-2222-2222-222222222205', '11111111-1111-1111-1111-111111111102', 'As Ondas do Oceano', 
'Feche os olhos e respire profundamente…

Imagine-se sentado à beira do oceano… observando as ondas irem e virem…

Cada onda é um evento na sua vida… algumas são suaves… outras são intensas…

Você não pode controlar as ondas… mas pode escolher como se posiciona diante delas…

Observe uma onda se aproximando… em vez de resistir… deixe-a passar por você…

Sinta como é diferente quando você não luta… quando você simplesmente permite…

As ondas continuam vindo… e você continua aqui… inteiro… presente…

A aceitação não é fraqueza… é a força de reconhecer o que está além do seu controle…

Respire fundo e traga essa paz para dentro de você…', 
4, 1, 5, ARRAY['paz', 'oceano', 'soltar'], true, now(), now()),

('22222222-2222-2222-2222-222222222206', '11111111-1111-1111-1111-111111111102', 'O Abraço do Presente', 
'Respire fundo e permita que seus olhos se fechem…

Neste momento… você está exatamente onde precisa estar…

Não no passado que já foi… não no futuro que ainda não chegou… mas aqui… agora…

Imagine que o momento presente é um abraço caloroso… envolvendo você completamente…

Dentro desse abraço… não há nada a corrigir… nada a melhorar… nada a resolver…

Apenas existir… apenas ser… apenas estar…

Sinta o alívio de soltar a necessidade de controle… a necessidade de perfeição…

Você é humano… e isso inclui imperfeições… falhas… e também uma beleza única…

Aceite este momento… aceite a si mesmo… exatamente como você é agora…', 
4, 1, 4, ARRAY['presente', 'autocompaixão', 'relaxamento'], true, now(), now()),

-- Autocompaixão (3)
('22222222-2222-2222-2222-222222222207', '11111111-1111-1111-1111-111111111103', 'O Amigo Interior', 
'Feche os olhos e respire fundo…

Pense em como você falaria com um amigo querido que está passando por um momento difícil…

Que palavras você usaria? Que tom de voz? Que gentileza?

Agora… volte essa mesma atenção para você mesmo…

Coloque a mão no coração e sinta o calor…

Diga internamente: "Eu mereço a mesma compaixão que ofereço aos outros"…

Você não precisa ser perfeito para merecer bondade… você já merece… simplesmente por existir…

Respire fundo e permita que essa gentileza se espalhe por todo o seu corpo…

Você está fazendo o melhor que pode com o que tem… e isso é suficiente…', 
4, 1, 5, ARRAY['gentileza', 'coração', 'autocompaixão'], true, now(), now()),

('22222222-2222-2222-2222-222222222208', '11111111-1111-1111-1111-111111111103', 'O Colo Seguro', 
'Respire profundamente e feche os olhos…

Imagine-se criança… pequeno… vulnerável… precisando de cuidado…

Agora… visualize seu eu adulto se aproximando dessa criança…

Olhe nos olhos dela com amor… sem julgamento… apenas compaixão…

Pegue essa criança no colo… abrace-a com carinho…

Diga a ela: "Você é amado… você é suficiente… você está seguro"…

Sinta o alívio dessa criança interior ao ser acolhida… finalmente vista… finalmente aceita…

Essa criança ainda vive em você… e ela ainda precisa do seu cuidado…

Respire fundo e prometa a ela que você estará presente… com gentileza… sempre…', 
4, 1, 4, ARRAY['criança interior', 'cura', 'acolhimento'], true, now(), now()),

('22222222-2222-2222-2222-222222222209', '11111111-1111-1111-1111-111111111103', 'A Voz Gentil', 
'Feche os olhos e observe seus pensamentos por um momento…

Quando você comete um erro… como você fala consigo mesmo?

Muitas vezes… somos nossos críticos mais severos…

Agora… imagine uma versão sua que é profundamente sábia e gentil…

Ela observa seus erros com compreensão… sabendo que falhar faz parte de crescer…

Ouça a voz dela dizendo: "Está tudo bem… você está aprendendo… eu estou aqui com você"…

Deixe essa voz substituir a crítica interna… pelo menos por agora…

Respire fundo e sinta a diferença… quando você se trata com bondade… tudo muda…

Você merece essa gentileza… todos os dias…', 
4, 2, 6, ARRAY['diálogo interno', 'gentileza', 'erros'], true, now(), now()),

-- Clareza (3)
('22222222-2222-2222-2222-222222222210', '11111111-1111-1111-1111-111111111104', 'O Lago Cristalino', 
'Respire fundo e feche os olhos…

Imagine-se diante de um lago de águas perfeitamente cristalinas…

A superfície está tão calma que você pode ver até o fundo…

Este lago representa sua mente… quando em paz… ela tem clareza total…

Observe como os pensamentos são como pequenas ondulações na água…

Quando você para de agitá-los… eles naturalmente se acalmam…

E quando a água fica parada… você consegue ver através dela… com nitidez…

O que você vê no fundo do lago? Que verdade se revela?

Respire fundo e traga essa clareza de volta… sabendo que ela sempre está disponível quando você se acalma…', 
4, 2, 6, ARRAY['mente', 'calma', 'clareza'], true, now(), now()),

('22222222-2222-2222-2222-222222222211', '11111111-1111-1111-1111-111111111104', 'A Névoa que se Dissipa', 
'Feche os olhos e respire profundamente…

Imagine que você está caminhando em uma manhã com névoa espessa…

Você mal consegue ver alguns passos à frente… e isso pode parecer confuso…

Mas continue caminhando… com calma… com confiança…

A cada passo que você dá… a névoa começa a se dissipar um pouco mais…

E então… um raio de sol atravessa… e a névoa vai embora…

De repente… você pode ver o caminho com total clareza…

A confusão era temporária… a clareza sempre estava lá… esperando ser revelada…

Respire fundo e confie que a clareza virá no momento certo…', 
4, 3, 7, ARRAY['caminho', 'confiança', 'paciência'], true, now(), now()),

('22222222-2222-2222-2222-222222222212', '11111111-1111-1111-1111-111111111104', 'A Bússola Interior', 
'Respire fundo e permita que seus olhos se fechem…

Imagine que no centro do seu peito existe uma bússola dourada…

Esta bússola não aponta para o norte geográfico… ela aponta para a sua verdade…

Quando você está alinhado com seus valores… a agulha fica estável…

Quando algo não está certo… ela oscila… indicando que você precisa ajustar a rota…

Agora… pense em uma decisão que precisa tomar…

Observe a bússola… para onde ela aponta?

Você já sabe a resposta… ela está dentro de você… sempre esteve…

Respire fundo e confie nessa orientação interior…', 
4, 4, 8, ARRAY['decisão', 'intuição', 'direção'], true, now(), now()),

-- Coragem (3)
('22222222-2222-2222-2222-222222222213', '11111111-1111-1111-1111-111111111105', 'O Guerreiro Interior', 
'Feche os olhos e respire fundo…

Imagine que dentro de você existe um guerreiro… forte… determinado… corajoso…

Ele não é agressivo… mas está pronto para enfrentar qualquer desafio…

Visualize esse guerreiro se levantando dentro de você…

Sinta sua coluna se endireitar… seus ombros se abrirem… sua presença se expandir…

Esse guerreiro conhece o medo… mas não é controlado por ele…

Ele age apesar do medo… porque sabe que do outro lado está o crescimento…

Respire fundo e sinta essa força correndo pelas suas veias…

Você tem coragem… ela está dentro de você… pronta para ser ativada…', 
4, 5, 9, ARRAY['força', 'guerreiro', 'determinação'], true, now(), now()),

('22222222-2222-2222-2222-222222222214', '11111111-1111-1111-1111-111111111105', 'A Ponte sobre o Abismo', 
'Respire profundamente e feche os olhos…

Imagine-se diante de um abismo profundo… do outro lado está algo que você deseja muito…

Entre você e seu objetivo existe uma ponte… ela parece frágil… balança com o vento…

O medo diz para você não atravessar… para ficar onde é seguro…

Mas você sabe que ficar parado também tem um custo…

Dê o primeiro passo na ponte… sinta-a sob seus pés…

Ela é mais forte do que parece… assim como você…

Continue caminhando… um passo de cada vez… sem olhar para baixo…

A coragem não é ausência de medo… é dar o próximo passo mesmo assim…

Você está atravessando… você está conseguindo…', 
4, 4, 8, ARRAY['desafio', 'superação', 'medo'], true, now(), now()),

('22222222-2222-2222-2222-222222222215', '11111111-1111-1111-1111-111111111105', 'O Leão Desperta', 
'Feche os olhos e respire fundo…

No centro do seu peito… dorme um leão… poderoso… majestoso…

Por muito tempo ele dormiu… enquanto você jogava pequeno… evitava riscos…

Mas agora… é hora de acordá-lo…

Sinta o calor no seu peito aumentando… o leão começa a se mover…

Ele se levanta… estica as patas… e solta um rugido que ecoa por todo o seu ser…

Este rugido é sua voz autêntica… sua força verdadeira… sua coragem plena…

Você não precisa mais se esconder… não precisa mais se diminuir…

Respire fundo e deixe o leão caminhar ao seu lado hoje…', 
4, 6, 10, ARRAY['poder', 'autenticidade', 'força'], true, now(), now()),

-- Desapego (3)
('22222222-2222-2222-2222-222222222216', '11111111-1111-1111-1111-111111111106', 'As Mãos Abertas', 
'Respire fundo e feche os olhos…

Olhe para suas mãos… elas estão fechadas… segurando algo com força…

O que você está segurando? Uma expectativa? Um resultado? Uma pessoa? O passado?

Sinta a tensão nos seus dedos… o esforço de manter esse aperto…

Agora… lentamente… comece a abrir as mãos…

Observe o que acontece quando você solta… o alívio… a leveza…

Desapego não é não se importar… é parar de tentar controlar o que não é seu…

Quando você abre as mãos… você cria espaço para receber algo novo…

Respire fundo e sinta a liberdade de soltar…', 
4, 2, 6, ARRAY['soltar', 'liberdade', 'controle'], true, now(), now()),

('22222222-2222-2222-2222-222222222217', '11111111-1111-1111-1111-111111111106', 'O Balão que Sobe', 
'Feche os olhos e respire profundamente…

Imagine que você está segurando um balão colorido… preso por uma corda na sua mão…

Este balão representa algo que você precisa deixar ir… uma preocupação… uma mágoa… uma expectativa…

Olhe para o balão e reconheça o que ele carrega…

Agradeça pelo que ele te ensinou… pelo papel que teve na sua jornada…

E então… solte a corda…

Observe o balão subindo… ficando cada vez menor no céu… até desaparecer…

Sinta o alívio nos seus ombros… a leveza no seu peito…

Algumas coisas precisam ir embora para que você possa seguir em frente…

Respire fundo e celebre essa libertação…', 
4, 2, 5, ARRAY['liberar', 'passado', 'leve'], true, now(), now()),

('22222222-2222-2222-2222-222222222218', '11111111-1111-1111-1111-111111111106', 'A Folha no Rio', 
'Respire fundo e permita que seus olhos se fechem…

Imagine-se às margens de um rio tranquilo…

Pegue uma folha seca e coloque nela um pensamento que está te pesando…

Pode ser uma preocupação… um arrependimento… uma expectativa…

Agora… deposite suavemente a folha na água…

Observe-a sendo levada pela correnteza… se afastando… ficando menor…

Você não precisa resolver tudo agora… você pode deixar o rio levar…

O universo é grande o suficiente para carregar o que você não consegue segurar…

Respire fundo e confie no fluxo natural das coisas…', 
4, 1, 5, ARRAY['fluir', 'soltar', 'natureza'], true, now(), now()),

-- Disciplina (3)
('22222222-2222-2222-2222-222222222219', '11111111-1111-1111-1111-111111111107', 'O Arquiteto da Rotina', 
'Feche os olhos e respire fundo…

Imagine-se como um arquiteto… construindo os dias da sua vida…

Cada hábito é um tijolo… cada rotina é uma parede… cada ritual é uma fundação…

Você não constrói uma casa em um dia… você a constrói tijolo por tijolo…

Visualize a estrutura que você está criando com suas ações diárias…

Ela é sólida? Ela te serve bem?

Agora… veja-se colocando um novo tijolo hoje… uma pequena ação… um passo consistente…

Não precisa ser grande… precisa ser regular…

A disciplina não é prisão… é a arquitetura da sua liberdade futura…

Respire fundo e comprometa-se com esse próximo tijolo…', 
4, 4, 8, ARRAY['hábitos', 'consistência', 'construção'], true, now(), now()),

('22222222-2222-2222-2222-222222222220', '11111111-1111-1111-1111-111111111107', 'O Mestre Artesão', 
'Respire profundamente e feche os olhos…

Imagine-se como um mestre artesão… alguém que dedica horas ao ofício…

Você não espera inspiração… você simplesmente começa…

Todo dia… você aparece na sua oficina… pega suas ferramentas… e trabalha…

Alguns dias o trabalho flui… outros dias é difícil…

Mas o mestre sabe que a excelência vem da prática consistente… não de momentos brilhantes isolados…

Visualize-se entrando na sua oficina interior… sentando-se… começando…

Não importa como você se sente… o que importa é que você está aqui…

Respire fundo e honre o poder de simplesmente aparecer… dia após dia…', 
4, 5, 9, ARRAY['prática', 'ofício', 'maestria'], true, now(), now()),

('22222222-2222-2222-2222-222222222221', '11111111-1111-1111-1111-111111111107', 'O Jardim Cultivado', 
'Feche os olhos e respire fundo…

Imagine que sua vida é um jardim… e você é o jardineiro…

Todo dia você escolhe o que plantar… o que regar… o que podar…

A disciplina é a água que você dá às plantas certas…

Se você rega todos os dias… mesmo um pouquinho… as plantas crescem…

Se você esquece por semanas… elas murcham…

Visualize seu jardim agora… quais plantas estão fortes? Quais precisam de mais atenção?

A disciplina não é sobre perfeição… é sobre cuidado regular…

Respire fundo e pergunte-se: o que precisa ser regado hoje?', 
4, 3, 7, ARRAY['cuidado', 'regular', 'crescimento'], true, now(), now()),

-- Energia (3)
('22222222-2222-2222-2222-222222222222', '11111111-1111-1111-1111-111111111108', 'A Fonte Vital', 
'Respire fundo e feche os olhos…

Imagine uma fonte de energia pura brilhando no centro do seu corpo…

Ela pulsa com luz dourada… vibrante… infinita…

A cada respiração… essa luz se expande… preenchendo cada célula…

Sinta seus braços se energizando… suas pernas ganhando força… sua mente ficando clara…

Esta energia é sua… ela não depende de circunstâncias externas…

Você pode acessá-la a qualquer momento… basta se conectar…

Respire fundo e sinta a vitalidade correndo por todo o seu ser…

Hoje você tem energia para o que precisa ser feito…', 
4, 5, 10, ARRAY['vitalidade', 'força', 'despertar'], true, now(), now()),

('22222222-2222-2222-2222-222222222223', '11111111-1111-1111-1111-111111111108', 'O Sol Interior', 
'Feche os olhos e respire profundamente…

No centro do seu peito existe um sol… radiante… poderoso…

Ele brilha independente do clima lá fora… independente das circunstâncias…

Sinta o calor desse sol se espalhando pelo seu corpo…

Seus músculos relaxam e ao mesmo tempo ganham força…

Sua mente clareia… sua disposição aumenta…

Este sol é sua energia vital… sua chama interior…

Quando você se sente cansado… é porque esqueceu que ele está lá…

Respire fundo e reconecte-se com seu sol interior… deixe-o brilhar forte hoje…', 
4, 6, 10, ARRAY['calor', 'força', 'radiante'], true, now(), now()),

('22222222-2222-2222-2222-222222222224', '11111111-1111-1111-1111-111111111108', 'O Despertar do Corpo', 
'Respire fundo e feche os olhos…

Leve sua atenção para os pés… sinta-os no chão… conectados à terra…

Agora imagine raízes saindo dos seus pés… penetrando o solo… chegando ao centro da terra…

De lá… uma energia vermelha e quente começa a subir pelas raízes…

Ela entra pelos seus pés… sobe pelas pernas… enche seu abdômen…

Continua subindo… pelo peito… pelos braços… até o topo da cabeça…

Seu corpo inteiro está vibrando com essa energia da terra…

Você está enraizado… forte… vitalizando…

Respire fundo e sinta essa conexão te sustentando durante todo o dia…', 
4, 4, 9, ARRAY['terra', 'raízes', 'corpo'], true, now(), now()),

-- Fluidez (3)
('22222222-2222-2222-2222-222222222225', '11111111-1111-1111-1111-111111111109', 'A Água que Contorna', 
'Feche os olhos e respire fundo…

Imagine-se como água… fluida… adaptável… persistente…

Quando encontra uma pedra no caminho… a água não luta contra ela…

Ela simplesmente contorna… encontra outro caminho… segue em frente…

Pense em um obstáculo na sua vida agora…

Em vez de empurrar com força… como você poderia contorná-lo?

A água sempre chega ao oceano… não importa quantas pedras encontre…

Você também chegará onde precisa ir… se permitir fluir…

Respire fundo e sinta essa fluidez entrando nas suas células…', 
4, 3, 7, ARRAY['água', 'adaptação', 'caminho'], true, now(), now()),

('22222222-2222-2222-2222-222222222226', '11111111-1111-1111-1111-111111111109', 'A Dança do Bambu', 
'Respire profundamente e feche os olhos…

Visualize um bambu alto e elegante… balançando ao vento…

O vento sopra forte… e o bambu se curva… quase tocando o chão…

Mas ele não quebra… porque é flexível… porque não resiste…

Quando o vento passa… ele volta à posição original… intacto… forte…

Você pode ser como o bambu… firme nas raízes… flexível no movimento…

A rigidez quebra… a fluidez sobrevive…

Respire fundo e sinta seu corpo se tornando mais flexível… mais adaptável…

Os ventos vão soprar… e você vai dançar com eles…', 
4, 2, 6, ARRAY['flexibilidade', 'bambu', 'vento'], true, now(), now()),

('22222222-2222-2222-2222-222222222227', '11111111-1111-1111-1111-111111111109', 'O Rio sem Pressa', 
'Feche os olhos e respire fundo…

Imagine um rio largo e calmo… fluindo sem pressa… sem esforço…

Ele não força seu caminho… ele simplesmente segue a gravidade natural…

Você pode viver assim também… seguindo o fluxo… confiando no processo…

Quando você para de forçar… as coisas acontecem com mais facilidade…

Visualize suas tensões como galhos presos na margem… o rio passa por eles sem se prender…

Você também pode passar por seus obstáculos assim… fluindo ao redor…

Respire fundo e solte a necessidade de controlar cada detalhe…

Deixe a vida fluir através de você…', 
4, 1, 5, ARRAY['rio', 'calma', 'confiança'], true, now(), now()),

-- Foco (3)
('22222222-2222-2222-2222-222222222228', '11111111-1111-1111-1111-111111111110', 'O Laser da Atenção', 
'Respire fundo e feche os olhos…

Imagine que sua atenção é um feixe de luz… como um laser…

Quando disperso… ele ilumina fracamente muitas coisas ao mesmo tempo…

Mas quando concentrado… ele tem poder para atravessar qualquer obstáculo…

Agora… concentre esse feixe em um único ponto… sua prioridade mais importante…

Sinta toda sua energia mental convergindo para esse ponto…

Tudo ao redor fica em segundo plano… existe apenas esse foco…

A distração perde força quando você direciona intencionalmente sua luz…

Respire fundo e mantenha esse laser apontado para o que realmente importa hoje…', 
4, 5, 9, ARRAY['atenção', 'concentração', 'prioridade'], true, now(), now()),

('22222222-2222-2222-2222-222222222229', '11111111-1111-1111-1111-111111111110', 'O Arqueiro Interior', 
'Feche os olhos e respire profundamente…

Imagine-se como um arqueiro… com um arco em mãos e uma flecha pronta…

Diante de você está um alvo… claro… definido… a uma distância perfeita…

Você puxa a corda do arco… sentindo a tensão aumentar…

Seus olhos estão fixos no centro do alvo… nada mais existe…

O mundo ao redor desaparece… só existe você e o alvo…

Respire fundo… e solte a flecha…

Ela voa certeira… atingindo o centro exato…

Esse é o poder do foco absoluto… quando você sabe onde quer chegar…

Traga essa precisão para suas ações de hoje…', 
4, 4, 8, ARRAY['alvo', 'precisão', 'intenção'], true, now(), now()),

('22222222-2222-2222-2222-222222222230', '11111111-1111-1111-1111-111111111110', 'O Santuário do Silêncio', 
'Respire fundo e feche os olhos…

Imagine que você entra em um santuário silencioso… longe de todo ruído…

Aqui dentro… os pensamentos dispersos não têm permissão para entrar…

Existe apenas espaço… silêncio… e clareza…

No centro deste santuário está uma mesa… e sobre ela… uma única tarefa…

Aproxime-se… sente-se diante dela… dê toda sua atenção…

Não há urgência… não há multitarefa… apenas presença total…

É assim que você faz seu melhor trabalho… é assim que você entra em fluxo…

Respire fundo e leve essa qualidade de atenção para fora do santuário…', 
4, 3, 7, ARRAY['silêncio', 'fluxo', 'presença'], true, now(), now()),

-- Gratidão (3)
('22222222-2222-2222-2222-222222222231', '11111111-1111-1111-1111-111111111111', 'O Inventário das Bênçãos', 
'Feche os olhos e respire fundo…

Vamos fazer um inventário do que você tem… não do que falta…

Pense no seu corpo… ele te carrega todos os dias… mesmo quando você esquece de agradecer…

Pense nas pessoas da sua vida… aquelas que te amam… que torcem por você…

Pense no que você tem acesso… comida… abrigo… este momento de paz…

Cada uma dessas coisas é um presente… uma bênção que muitos não têm…

Sinta seu coração se enchendo de gratidão… como uma taça transbordando…

A gratidão muda a lente pela qual você vê o mundo…

Respire fundo e carregue essa sensação de abundância com você hoje…', 
4, 2, 7, ARRAY['bênçãos', 'reconhecimento', 'abundância'], true, now(), now()),

('22222222-2222-2222-2222-222222222232', '11111111-1111-1111-1111-111111111111', 'O Presente do Presente', 
'Respire profundamente e feche os olhos…

Este momento exato… esta respiração… é um presente…

Você está vivo… você está consciente… você pode sentir e pensar e amar…

Quantos momentos assim você deixou passar sem perceber?

Agora… faça diferente… esteja totalmente aqui…

Agradeça pelo ar que entra nos seus pulmões…

Agradeça pelo coração que bate sem você precisar pedir…

Agradeça pelo milagre silencioso da existência…

Respire fundo e deixe essa gratidão colorir todo o seu dia…

Você está vivendo o momento que um dia será uma lembrança preciosa…', 
4, 1, 5, ARRAY['momento', 'presença', 'milagre'], true, now(), now()),

('22222222-2222-2222-2222-222222222233', '11111111-1111-1111-1111-111111111111', 'A Carta de Agradecimento', 
'Feche os olhos e respire fundo…

Pense em alguém que fez diferença na sua vida… alguém que te ajudou a chegar onde você está…

Pode ser um familiar… um professor… um amigo… ou até um desconhecido…

Imagine que você está escrevendo uma carta para essa pessoa…

O que você diria? Como expressaria sua gratidão?

Sinta o calor no seu coração enquanto pensa nessa pessoa…

A gratidão que você sente… mesmo que nunca dita em voz alta… tem poder…

Ela te conecta com o que há de melhor na humanidade…

Respire fundo e prometa expressar mais gratidão às pessoas que importam…', 
4, 2, 6, ARRAY['pessoas', 'conexão', 'expressão'], true, now(), now()),

-- Integridade (3)
('22222222-2222-2222-2222-222222222234', '11111111-1111-1111-1111-111111111112', 'O Alinhamento Interior', 
'Respire fundo e feche os olhos…

Imagine uma linha vertical de luz atravessando seu corpo…

Ela começa acima da sua cabeça… passa pelo centro do seu ser… e desce até o solo…

Esta linha representa o alinhamento entre quem você é… o que você diz… e o que você faz…

Quando essas três coisas estão na mesma linha… você está íntegro…

Observe agora… existe algum desalinhamento? Algum lugar onde você está dividido?

Respire fundo e sinta essa linha de luz te realinhando…

Integridade é quando você é o mesmo por dentro e por fora…

Traga essa coerência para todas as suas ações de hoje…', 
4, 3, 7, ARRAY['coerência', 'alinhamento', 'verdade'], true, now(), now()),

('22222222-2222-2222-2222-222222222235', '11111111-1111-1111-1111-111111111112', 'A Palavra Sagrada', 
'Feche os olhos e respire profundamente…

Suas palavras têm poder… elas criam e destroem… elas conectam e afastam…

Quando você diz que vai fazer algo… e faz… você constrói confiança…

Quando você promete e não cumpre… você erode seu próprio poder…

Visualize suas palavras como sementes que você planta no mundo…

Que tipo de sementes você está plantando?

Agora… faça um compromisso silencioso… de honrar mais suas palavras…

Não prometa o que não pode cumprir… mas cumpra tudo o que prometer…

Respire fundo e sinta o peso e a beleza de uma palavra honrada…', 
4, 4, 8, ARRAY['palavra', 'compromisso', 'honra'], true, now(), now()),

('22222222-2222-2222-2222-222222222236', '11111111-1111-1111-1111-111111111112', 'O Espelho da Consciência', 
'Respire fundo e feche os olhos…

Imagine-se diante de um espelho especial… que reflete não sua aparência… mas suas intenções…

Olhe profundamente… o que você vê?

Quais são suas motivações verdadeiras? Por que você faz o que faz?

Não há julgamento aqui… apenas honestidade…

A integridade começa quando você é honesto consigo mesmo…

Mesmo quando a verdade é desconfortável… ela é libertadora…

Respire fundo e agradeça por ter a coragem de se olhar de verdade…

Essa clareza interior é a base de uma vida íntegra…', 
4, 2, 6, ARRAY['honestidade', 'motivação', 'consciência'], true, now(), now()),

-- Intuição (3)
('22222222-2222-2222-2222-222222222237', '11111111-1111-1111-1111-111111111113', 'A Voz Silenciosa', 
'Feche os olhos e respire fundo…

Em algum lugar dentro de você existe uma voz que sabe…

Ela não grita… não exige atenção… ela simplesmente sussurra…

Mas quando você para e escuta… ela sempre tem algo valioso a dizer…

Essa é sua intuição… sua sabedoria interior… seu guia interno…

Faça uma pergunta silenciosa agora… algo que você precisa de orientação…

E então… espere… sem forçar… sem analisar…

Deixe a resposta emergir… pode vir como uma sensação… uma imagem… uma certeza…

Respire fundo e confie no que você recebeu… sua intuição raramente erra…', 
4, 2, 6, ARRAY['voz interior', 'sabedoria', 'escuta'], true, now(), now()),

('22222222-2222-2222-2222-222222222238', '11111111-1111-1111-1111-111111111113', 'O Sábio Interior', 
'Respire profundamente e feche os olhos…

Imagine que você está caminhando por uma floresta antiga…

No centro desta floresta existe uma clareira… e ali está sentado um sábio…

Este sábio é uma parte de você… a parte que viu tudo… que compreende tudo…

Aproxime-se com respeito… sente-se diante dele…

Você pode fazer qualquer pergunta… ele tem todas as respostas que você precisa…

Pergunte… e ouça…

A resposta pode surpreendê-lo… mas ressoa como verdade…

Respire fundo e agradeça ao sábio… sabendo que ele está sempre disponível…', 
4, 1, 5, ARRAY['sábio', 'floresta', 'respostas'], true, now(), now()),

('22222222-2222-2222-2222-222222222239', '11111111-1111-1111-1111-111111111113', 'O Corpo que Sabe', 
'Feche os olhos e respire fundo…

Sua mente pode duvidar… pode analisar em excesso… pode se confundir…

Mas seu corpo… ele sabe…

Leve sua atenção para o seu corpo agora…

Pense em uma decisão que você está enfrentando…

Observe como seu corpo reage a cada opção…

Uma opção pode trazer tensão no peito… aperto no estômago…

Outra pode trazer expansão… leveza… respiração mais profunda…

Seu corpo está te dando sinais claros… aprenda a ouvi-los…

Respire fundo e confie na sabedoria do seu corpo…', 
4, 3, 7, ARRAY['corpo', 'sinais', 'decisão'], true, now(), now()),

-- Paciência (3)
('22222222-2222-2222-2222-222222222240', '11111111-1111-1111-1111-111111111114', 'A Semente Que Germina', 
'Respire fundo e feche os olhos…

Imagine uma semente plantada na terra…

Ela não brota imediatamente… ela precisa de tempo… de escuridão… de paciência…

Dia após dia… invisível para os olhos… ela está trabalhando…

Suas raízes vão se aprofundando… sua energia vai se acumulando…

E então… um dia… ela rompe a superfície… e encontra a luz…

Suas metas são assim… seu crescimento é assim…

Muito do seu progresso é invisível… mas está acontecendo…

Respire fundo e confie no tempo… confie no processo… confie na semente que você plantou…', 
4, 2, 6, ARRAY['semente', 'tempo', 'crescimento'], true, now(), now()),

('22222222-2222-2222-2222-222222222241', '11111111-1111-1111-1111-111111111114', 'O Artesão do Tempo', 
'Feche os olhos e respire profundamente…

Imagine um artesão que cria obras de arte meticulosas…

Ele não tem pressa… cada detalhe recebe a atenção que merece…

Ele sabe que a beleza verdadeira não pode ser apressada…

Você também está criando algo… sua vida… sua transformação…

E como o artesão… você precisa dar tempo ao tempo…

A ansiedade de querer resultados imediatos é o inimigo da maestria…

Respire fundo e escolha a qualidade acima da velocidade…

O que é feito com paciência dura muito mais…', 
4, 3, 7, ARRAY['artesão', 'qualidade', 'maestria'], true, now(), now()),

('22222222-2222-2222-2222-222222222242', '11111111-1111-1111-1111-111111111114', 'O Bambu Chinês', 
'Respire fundo e feche os olhos…

Você conhece a história do bambu chinês?

Nos primeiros cinco anos após ser plantado… ele não aparece na superfície…

Você rega… cuida… espera… e nada visível acontece…

Mas debaixo da terra… suas raízes estão se expandindo… se fortalecendo…

E então… no sexto ano… ele cresce trinta metros em apenas seis semanas…

Ele levou cinco anos ou seis semanas para crescer? Ele levou tudo isso…

Sua jornada pode parecer invisível agora… mas as raízes estão crescendo…

Respire fundo e continue regando… continue cuidando… continue confiando…', 
4, 2, 5, ARRAY['bambu', 'raízes', 'confiança'], true, now(), now()),

-- Paz Interior (3)
('22222222-2222-2222-2222-222222222243', '11111111-1111-1111-1111-111111111115', 'O Templo Interior', 
'Feche os olhos e respire fundo…

Dentro de você existe um lugar de paz absoluta… um templo interior…

Não importa o que acontece lá fora… aqui dentro há silêncio… calma… serenidade…

Visualize-se entrando neste templo… as portas se fecham atrás de você…

Os ruídos do mundo ficam do lado de fora… você está seguro…

Sente-se no centro deste espaço sagrado… respire profundamente…

Aqui você pode descansar… aqui você pode ser…

A paz não depende de circunstâncias… ela existe dentro de você… sempre disponível…

Respire fundo e traga essa paz para o seu dia…', 
4, 1, 4, ARRAY['templo', 'silêncio', 'segurança'], true, now(), now()),

('22222222-2222-2222-2222-222222222244', '11111111-1111-1111-1111-111111111115', 'A Montanha Imóvel', 
'Respire profundamente e feche os olhos…

Imagine-se como uma grande montanha… firme… sólida… imóvel…

Os ventos sopram à sua volta… as tempestades vêm e vão…

Mas você permanece… estável… enraizado… inabalável…

As circunstâncias da vida são como o clima… sempre mudando…

Mas seu centro… sua essência… pode permanecer em paz…

Você não precisa ser sacudido por cada vento que passa…

Você pode escolher ser a montanha… presente… calma… forte…

Respire fundo e sinta essa estabilidade interior…', 
4, 2, 6, ARRAY['montanha', 'estabilidade', 'calma'], true, now(), now()),

('22222222-2222-2222-2222-222222222245', '11111111-1111-1111-1111-111111111115', 'O Centro do Furacão', 
'Feche os olhos e respire fundo…

Imagine um furacão poderoso girando com força…

Ventos violentos… destruição… caos…

Mas no centro exato do furacão… existe um lugar de absoluta calma…

Nenhum vento… nenhuma chuva… apenas silêncio perfeito…

Você pode viver assim… no centro do seu próprio furacão…

O caos pode girar ao seu redor… mas você permanece no olho da tempestade…

Isso requer prática… requer escolha consciente…

Respire fundo e encontre seu centro agora… aquele lugar de paz inalterável…', 
4, 1, 5, ARRAY['furacão', 'centro', 'calma'], true, now(), now()),

-- Presença (3)
('22222222-2222-2222-2222-222222222246', '11111111-1111-1111-1111-111111111116', 'O Agora é Suficiente', 
'Respire fundo e feche os olhos…

Neste exato momento… você não tem problemas…

Problemas existem no passado… onde você revive dores… ou no futuro… onde você antecipa medos…

Mas agora… neste preciso instante… você está bem…

Sinta o ar entrando nos seus pulmões… isso é o agora…

Sinta seu corpo apoiado onde você está… isso é o agora…

Ouça os sons ao seu redor… isso é o agora…

O agora é o único lugar onde a vida realmente acontece…

Respire fundo e ancore-se neste momento… ele é tudo o que você realmente tem…', 
4, 1, 5, ARRAY['momento', 'âncora', 'agora'], true, now(), now()),

('22222222-2222-2222-2222-222222222247', '11111111-1111-1111-1111-111111111116', 'Os Cinco Sentidos', 
'Feche os olhos por um momento… e depois abra-os suavemente…

Vamos usar seus sentidos para te trazer ao presente…

Primeiro… veja cinco coisas ao seu redor… qualquer coisa… observe os detalhes…

Agora feche os olhos e ouça quatro sons… próximos ou distantes…

Toque três texturas diferentes… sinta com curiosidade…

Perceba dois cheiros… o que seu nariz detecta?

E por fim… qual o sabor na sua boca agora?

Seus sentidos são portais para o momento presente…

Sempre que sua mente viajar para longe… use os sentidos para voltar ao agora…', 
4, 2, 6, ARRAY['sentidos', 'ancoragem', 'consciência'], true, now(), now()),

('22222222-2222-2222-2222-222222222248', '11111111-1111-1111-1111-111111111116', 'A Respiração Consciente', 
'Respire fundo e feche os olhos…

A respiração é o fio que te conecta ao presente…

Ela está sempre aqui… sempre agora… sempre disponível…

Observe sua respiração entrando… enchendo seus pulmões…

Observe a pausa natural… e então a exalação… o esvaziamento…

Você não precisa mudar nada… apenas observar…

Quando sua mente vagar… gentilmente volte à respiração…

Cada retorno é uma vitória… cada momento de consciência é presença…

A respiração é seu professor mais paciente… sempre te chamando de volta ao agora…', 
4, 1, 4, ARRAY['respiração', 'consciência', 'momento'], true, now(), now()),

-- Prioridade (3)
('22222222-2222-2222-2222-222222222249', '11111111-1111-1111-1111-111111111117', 'As Pedras Grandes Primeiro', 
'Feche os olhos e respire fundo…

Imagine um pote de vidro… ele representa seu dia…

Você tem pedras grandes… pedras médias… areia e água…

Se você colocar a areia primeiro… não sobrará espaço para as pedras grandes…

Mas se você começar pelas pedras grandes… tudo se encaixa…

Quais são suas pedras grandes? O que realmente importa?

Visualize-se colocando essas prioridades primeiro no seu pote…

As urgências que parecem gritar são apenas areia… elas podem esperar…

Respire fundo e comprometa-se a honrar o que é verdadeiramente importante…', 
4, 4, 8, ARRAY['prioridades', 'importante', 'escolha'], true, now(), now()),

('22222222-2222-2222-2222-222222222250', '11111111-1111-1111-1111-111111111117', 'O Não Sagrado', 
'Respire profundamente e feche os olhos…

Cada vez que você diz sim para algo… você está dizendo não para outra coisa…

Seu tempo é limitado… sua energia também…

Um sim automático para tudo é na verdade um não para suas prioridades…

Visualize as demandas da sua vida como pessoas em uma fila…

Você não pode atender a todos… quem entra primeiro?

Praticar o não é proteger o que é sagrado…

Respire fundo e dê-se permissão para escolher… para priorizar… para dizer não…

Seu sim ganha poder quando seu não é respeitado…', 
4, 3, 7, ARRAY['limites', 'escolha', 'tempo'], true, now(), now()),

('22222222-2222-2222-2222-222222222251', '11111111-1111-1111-1111-111111111117', 'O Filtro da Essência', 
'Feche os olhos e respire fundo…

Imagine que você tem um filtro mágico na sua mente…

Tudo o que passa por ele é separado em duas categorias…

De um lado: o essencial… o que move você para onde quer ir…

Do outro lado: o superficial… o que apenas consome tempo e energia…

Quando você olha para sua lista de tarefas através desse filtro… o que sobra?

Menos do que você imagina… mas com muito mais impacto…

Respire fundo e permita que esse filtro guie suas decisões hoje…

Fazer menos… mas fazer o que importa… isso é sabedoria…', 
4, 4, 8, ARRAY['essencial', 'filtro', 'sabedoria'], true, now(), now()),

-- Rendição (3)
('22222222-2222-2222-2222-222222222252', '11111111-1111-1111-1111-111111111118', 'O Salto de Fé', 
'Respire fundo e feche os olhos…

Imagine-se no topo de um penhasco… diante de um oceano infinito…

Você não consegue ver o fundo… não sabe o que há lá embaixo…

Sua mente quer controlar… quer garantias… quer saber antes de se mover…

Mas às vezes… a vida pede um salto de fé…

Visualize-se saltando… sentindo o ar no rosto… o medo e a liberdade se misturando…

E então… você pousa suavemente… algo te sustentou… você está seguro…

A rendição não é desistência… é confiança em algo maior que sua compreensão…

Respire fundo e pergunte-se: onde você está sendo chamado a saltar?', 
4, 2, 6, ARRAY['confiança', 'salto', 'fé'], true, now(), now()),

('22222222-2222-2222-2222-222222222253', '11111111-1111-1111-1111-111111111118', 'Que Seja Feita a Vontade', 
'Feche os olhos e respire profundamente…

Existe uma parte sua que quer controlar tudo… cada resultado… cada detalhe…

Mas a vida tem seus próprios planos… e às vezes eles são melhores que os seus…

Imagine que você está segurando um controle remoto da sua vida…

Todos os botões… tentando desesperadamente controlar cada cena…

Agora… deposite esse controle em uma mão maior… em uma sabedoria maior…

Diga internamente: "Farei minha parte… e confiarei no processo"…

Isso não é passividade… é parceria com a vida…

Respire fundo e sinta o alívio de não precisar controlar tudo…', 
4, 1, 5, ARRAY['controle', 'confiança', 'soltar'], true, now(), now()),

('22222222-2222-2222-2222-222222222254', '11111111-1111-1111-1111-111111111118', 'A Correnteza da Vida', 
'Respire fundo e feche os olhos…

Imagine que você está em um barco… navegando por um rio…

Você pode remar a favor da correnteza… ou contra ela…

Remar contra cansa… esgota… e muitas vezes não leva a lugar algum…

Remar a favor… é aceitar a direção natural das coisas…

A rendição é isso… parar de lutar contra o fluxo…

Você ainda pode usar seu remo… para ajustar o curso… para evitar obstáculos…

Mas você não luta mais contra o rio inteiro…

Respire fundo e sinta seu corpo relaxando enquanto você se entrega ao fluxo…', 
4, 2, 6, ARRAY['rio', 'fluxo', 'aceitar'], true, now(), now()),

-- Silêncio (3)
('22222222-2222-2222-2222-222222222255', '11111111-1111-1111-1111-111111111119', 'O Espaço Entre os Sons', 
'Feche os olhos e respire fundo…

Ouça os sons ao seu redor… quaisquer que sejam…

Agora… em vez de focar nos sons… foque no espaço entre eles…

No silêncio que existe antes de cada som… e depois dele…

O silêncio não é ausência… é o palco onde tudo acontece…

Sem ele… não haveria música… não haveria significado…

Sua mente é assim também… ela precisa de espaço entre os pensamentos…

Nesses espaços está a clareza… a criatividade… a paz…

Respire fundo e deixe mais silêncio entrar na sua mente hoje…', 
4, 1, 4, ARRAY['silêncio', 'espaço', 'calma'], true, now(), now()),

('22222222-2222-2222-2222-222222222256', '11111111-1111-1111-1111-111111111119', 'O Santuário do Vazio', 
'Respire profundamente e feche os olhos…

Imagine um espaço completamente vazio… sem móveis… sem objetos… sem distrações…

Este é o santuário do vazio… e ele é precioso…

Nossa cultura tem medo do vazio… tenta preenchê-lo com ruído… com atividade… com estímulo…

Mas o vazio não é falta… é potencial…

É do vazio que nasce a criação… é no silêncio que surge a clareza…

Sente-se neste espaço vazio… sem nada para fazer… ninguém para impressionar…

Respire fundo e aprecie a beleza da simplicidade absoluta…

O silêncio é um presente que você pode se dar todos os dias…', 
4, 1, 4, ARRAY['vazio', 'simplicidade', 'potencial'], true, now(), now()),

('22222222-2222-2222-2222-222222222257', '11111111-1111-1111-1111-111111111119', 'A Floresta Silenciosa', 
'Feche os olhos e respire fundo…

Imagine-se caminhando em uma floresta coberta de neve…

Os galhos estão pesados… o céu está cinza… e há um silêncio profundo…

Seus passos são abafados pela neve… cada respiração é visível no ar frio…

Não há carros… não há vozes… não há notificações…

Apenas você… a floresta… e o silêncio…

Sinta como sua mente vai se acalmando naturalmente…

O silêncio exterior convida o silêncio interior…

Respire fundo e traga essa quietude para dentro de você…', 
4, 1, 5, ARRAY['floresta', 'neve', 'quietude'], true, now(), now()),

-- Verdade (3)
('22222222-2222-2222-2222-222222222258', '11111111-1111-1111-1111-111111111120', 'O Espelho da Alma', 
'Respire fundo e feche os olhos…

Imagine-se diante de um espelho que reflete não seu corpo… mas sua alma…

Olhe profundamente… sem medo… sem vergonha…

O que você vê? Quais verdades estão escritas ali?

Talvez você veja força que não reconhecia… ou feridas que ainda precisa curar…

Talvez você veja desejos que nunca admitiu… ou talentos que deixou adormecidos…

A verdade sobre quem você é pode ser desconfortável… mas é sempre libertadora…

Respire fundo e agradeça por ter a coragem de se olhar de verdade…

Conhecer a si mesmo é o primeiro passo para qualquer transformação real…', 
4, 2, 6, ARRAY['autoconhecimento', 'alma', 'coragem'], true, now(), now()),

('22222222-2222-2222-2222-222222222259', '11111111-1111-1111-1111-111111111120', 'As Máscaras que Caem', 
'Feche os olhos e respire profundamente…

Ao longo da vida… você coletou máscaras…

Máscaras para agradar… para se proteger… para pertencer…

Algumas foram úteis em algum momento… outras já perderam a função…

Visualize-se tirando uma dessas máscaras agora…

Sinta o ar fresco tocando seu rosto verdadeiro…

Pode ser vulnerável no início… pode parecer estranho…

Mas debaixo de todas as máscaras… existe você… autêntico… real… suficiente…

Respire fundo e pergunte-se: qual máscara eu posso tirar hoje?', 
4, 3, 7, ARRAY['autenticidade', 'vulnerabilidade', 'verdade'], true, now(), now()),

('22222222-2222-2222-2222-222222222260', '11111111-1111-1111-1111-111111111120', 'A Voz da Honestidade', 
'Respire fundo e feche os olhos…

Dentro de você existe uma voz que nunca mente…

Ela pode ser silenciada… ignorada… abafada por outras vozes…

Mas ela nunca desaparece… ela sempre sabe a verdade…

Convide essa voz para falar agora… pergunte a ela o que ela precisa te dizer…

Ouça sem julgamento… ouça com curiosidade…

A verdade pode ser inconveniente… mas ela é sempre a base do crescimento real…

Mentir para si mesmo mantém você preso… a honestidade te liberta…

Respire fundo e agradeça por essa voz que nunca te abandona…', 
4, 2, 6, ARRAY['honestidade', 'voz interior', 'liberdade'], true, now(), now())

ON CONFLICT (id) DO NOTHING;